### ISSUE TITLE
Правильно ли я понял?

### ISSUE THREAD

**Issue by yuristsepaniuk** [sergey-moiseyenko/news-portal-api#2]
В diskdb articles хранится один объект внутри массива? Чем монго поможет Вам? Кажется нет понятия зачем мы строим индексы. Есть база данных diskDB, мы должны хранить данные в том виде, который диктует diskDB. Генерируется _id для каждой новой статьи. Индексы строим относительно этих id! Т.е. BE полностью выгружает один объект в память у Вас, чтобы потом работать с ним? Зачем нам тогда diskDB? Можно просто сохранять на диск. Вы не поняли возможности diskDB. 
Готов ответить на Ваши вопросы в этом открытом issue. Язык русский.

Thx
-Yura

**Comment by 4en1x** [comment]
У меня та же ошибка, поэтому напишу здесь. Юра, всё же не очень понятно, что ты имеешь ввиду. У нас сейчас есть индексация, и, например, в случае новости  мы храним по  id-шке саму новость(c id внутри) . Но если мы сейчас начнём хранить эти новости по _id , то не совсем понятно, как это должно работать -  мы должны хранить в  объекте, который соответствует этому _id , то же самое _id, но мы сейчас его генерируем на клиенте. Или ты предлагаешь заполнять его после того, как мы положили объект в diskdb?
Остальное в целом понятно, но вот этот момент хотелось бы уточнить.

**Comment by yuristsepaniuk** [comment]
Пару фраз:
1. мы не должны генерить id на клиенте. Генерит id DiskDB.
2. мы не должны хранить большой объект в articles.json
3. данные индекса можно хранить в виде одного большого объекта в tagIndex.json и не генерить базой ids.

**Comment by sergey-moiseyenko** [comment]
Юрий, привет, хотел уточнить реализацию auth. 
Так как мы разрабатываем BE по принципам REST, то использование passport-local и сессий не подходит под архитектуру нашего приложения (одно из требований к архитектуре REST: информация о состоянии клиента на сервере не хранится).

Считаю, что для этого больше подходит passport-http или passport-jwt. Что скажешь?
