### ISSUE TITLE
About 11 task

### ISSUE THREAD

**Issue by sergey-moiseyenko** [sergey-moiseyenko/news-portal-api#3]
Юрий, привет, хотел уточнить реализацию auth.
Так как мы разрабатываем BE по принципам REST, то использование `passport-local` и сессий не подходит под архитектуру нашего приложения (одно из требований к архитектуре REST: информация о состоянии клиента на сервере не хранится).

Считаю, что для этого больше подходит `passport-http` или `passport-jwt`. Что скажешь?

**Comment by yuristsepaniuk** [comment]
Привет, Сергей :) 
`одно из требований к архитектуре REST: информация о состоянии клиента на сервере не хранится`

Все верно, это и есть реализация при помощи express-session с default in memory store, плюс passport-local.

Но ты не прав вот где, было бы правильно сказать, что нам это не подходит, потому что default in memory store используем, а не passport-local. На лекции я пояснял, что не стоит хранить состояние юзера на сервере, как это делает in memory store, стоит хранить состояние в базе. passport-local позволяет тебе хранить в cookie то, что ты запишешь туда? 

В чем разница passport-local или passport-jwt? json web token идеально использовать на авторизации сервер ту сервер. Ну да, можно юзать и на стороне клиент ту сервер, но поддержку сессии ты все равно должен сделать, просто ты собираешься сделать опасную вещь, json web token отдать клиенту, который старбакс может также украсть как и твой SID от стратегии passport-local. С точки зрения SID или JWT нет разницы, ты просто поддерживаешь сессию при помощи JWT или SID. Но в любом случае по причине security ты должен инвалидировать JWT переодически, также как и SID. 

Если между SID и JWT нет разницы, то не глупо ли браузеру давать доступ к такой ценной инфе, как JWT. Я сомневаюсь, что JWT так часто инвалидейтят при работе server to server, поэтому тут и нет смысла поддерживать сессию между серваками, и не нужно инвалидейтить JWT. Иначе тебе прийдется между серверами гонять куки и это странно, поэтому если сервер общается с другим сервером в закрытой сети, то JWT отличный вариант.

Резюме:
1. JWT на клиенте без инвалидейта - смерть!
2. JWT круто без инвалидейта, если коннект server to server внутри прайвит сети.
3. JWT на клиенте с инвалидейтом, в чем разница с SID? Нет разницы, это поддержка сессии, чувак :)
4. Если server to server через незащищенный канал, можно конечно обсуждать, что удобнее, но это вряд ли будут куки, скорее это будет JWT с частотой инвалидации и re-connection.


NOTE: passport-http это бэйсик стратегия, которая является трешаковой, basic auth - самый ненадеждый способ комуникации, браузеры показывают ужасный попап при авторизации API запросов, потом кэшируют их и добавляют этот хидер в запросы. Вообще болото!

**Comment by sergey-moiseyenko** [comment]
Юрий, спасибо за ответ, но `passport-http` - это также и `digest` стратегия, которую я планировал использовать и которая надежнее `basic`.

**Comment by yuristsepaniuk** [comment]
В данном случае это выглядит как уход от реализации всего руками. Задача стоит юзать стратегию с поддержкой сессии, хранимой в базе. Решение digest или basic не будет использовано ни на одном продакшен проекте.

**Comment by yuristsepaniuk** [comment]
Чем digest лучше, зашифрованного хранения пароля при помощи passport-local?

**Comment by sergey-moiseyenko** [comment]
Стратегия digest работает по принципу запрос-ответ + избегаем отправки пароля  в текстовом формате(одностороннее шифрование)

**Comment by yuristsepaniuk** [comment]
Я на лекции говорил, что не стоит хранить пароль в любом виде на клиенте, он должен передаваться только один раз. Дальнейшее взаимодействие с сервером по SID.
